const $=id=>document.getElementById(id);
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function pct(n){if(n==null)return '<span class="mono">n/a</span>';const v=Number(n);return `<span class="${v>=0?'up':'down'} mono">${v>=0?'+':''}${v.toFixed(2)}%</span>`}
function vol(n){if(n>=1e9)return(n/1e9).toFixed(1)+'B';if(n>=1e6)return(n/1e6).toFixed(0)+'M';if(n>=1e3)return(n/1e3).toFixed(0)+'K';return String(Math.round(n||0))}
function chip(value){const safe=escapeHtml(value||'?'),map={acelera:'acelera',esfriou:'esfriou','cai mais':'cai',reagiu:'reagiu'};return `<span class="chip ${map[value]||''}">${safe}</span>`}
function spark(values){if(!values||values.length<2)return '';const w=84,h=28,p=2,min=Math.min(...values),max=Math.max(...values),span=max-min||1,points=values.map((v,i)=>`${(p+i*(w-2*p)/(values.length-1)).toFixed(1)},${(h-p-(v-min)/span*(h-2*p)).toFixed(1)}`).join(' '),color=values.at(-1)>=values[0]?'#3ee0a0':'#ff6b7a';return `<svg class="spark" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" aria-hidden="true"><polyline fill="none" stroke="${color}" stroke-width="1.6" points="${points}"/></svg>`}
function block(title,data){if(data.error)return `<div class="err">${escapeHtml(data.error)}</div>`;const rows=items=>items.map((x,i)=>`<tr><td class="mono">${i+1}</td><td><b>${escapeHtml(x.base)}</b></td><td>${spark(x.spark)}</td><td>${pct(x.var24)}</td><td>${pct(x.var1h)}</td><td>${chip(x.ritmo)}</td><td class="mono">${vol(x.volume)}</td></tr>`).join('');const table=items=>`<div class="table-wrap"><table><thead><tr><th>#</th><th>Moeda</th><th>24h</th><th>24h %</th><th>1h</th><th>Ritmo</th><th>Vol</th></tr></thead><tbody>${rows(items)}</tbody></table></div>`;return `<div class="hd"><b>${title}</b><span class="tag">${data.n} pares · ${data.pumps} pumps filtrados</span></div><div class="hd" style="padding-bottom:0;border:0"><span class="tag">MAIORES ALTAS</span></div>${table(data.altas)}<div class="hd" style="padding-bottom:0;border:0"><span class="tag">MAIORES QUEDAS</span></div>${table(data.baixas)}`}
let busy=false;
async function tick(manual=false){if(busy)return;busy=true;const button=$("refresh");button.disabled=true;if(manual)button.textContent="Atualizando…";try{const response=await fetch(`/api/crypto-radar${manual?`?t=${Date.now()}`:''}`);const data=await response.json();if(!response.ok)throw new Error(data.erro||`HTTP ${response.status}`);$("clock").textContent='atualizado '+data.hora;$("binance").innerHTML=block('Binance USDT',data.binance);$("cdc").innerHTML=block('Crypto.com USDT',data.cdc)}catch(error){$("clock").textContent='falha de rede';const message=`<div class="err">Não foi possível atualizar: ${escapeHtml(error.message)}</div>`;$("binance").innerHTML=message;$("cdc").innerHTML=message}finally{busy=false;button.disabled=false;button.textContent="Atualizar"}}
$("refresh").addEventListener("click",()=>tick(true));tick();setInterval(()=>tick(false),45000);

